/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User login */
        post: operations["AuthPublicController_login_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** SOCIO-only user signup */
        post: operations["AuthPublicController_signup_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Refresh tokens */
        get: operations["AuthPublicController_refreshTokens_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active users for login selector */
        get: operations["AuthPublicController_getActiveUsers_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User logout */
        post: operations["AuthPublicController_logout_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users (SOCIO only) */
        get: operations["UserAdminController_findAll_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/user/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user by ID (SOCIO only) */
        get: operations["UserAdminController_findById_v1"];
        put?: never;
        post?: never;
        /** Delete user (soft delete) */
        delete: operations["UserAdminController_deleteUser_v1"];
        options?: never;
        head?: never;
        /** Update user (SOCIO only) */
        patch: operations["UserAdminController_updateUser_v1"];
        trace?: never;
    };
    "/v1/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user profile */
        get: operations["UserPublicController_getProfile_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update user profile */
        put: operations["UserPublicController_updateUser_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List clientes with optional filters */
        get: operations["ClientesPublicController_findAll_v1"];
        put?: never;
        /** Create cliente with impuestos (SOCIO only) */
        post: operations["ClientesAdminController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clientes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get cliente by ID */
        get: operations["ClientesPublicController_findById_v1"];
        put?: never;
        post?: never;
        /** Soft-delete cliente (SOCIO only) */
        delete: operations["ClientesAdminController_delete_v1"];
        options?: never;
        head?: never;
        /** Update cliente (SOCIO only) */
        patch: operations["ClientesAdminController_update_v1"];
        trace?: never;
    };
    "/v1/clientes/{id}/legajo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get complete cliente legajo (with impuestos, encargado, supervisor) */
        get: operations["ClientesPublicController_findLegajo_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clientes/afip/{cuit}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Look up CUIT data from AFIP mock service */
        get: operations["ClientesAfipController_getAfipData_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiSuccessResponseDto: {
            /**
             * @description HTTP status code
             * @example 200
             */
            statusCode: number;
            /**
             * @description Response message
             * @example Operation successful
             */
            message: string;
            /**
             * @description Timestamp of the response
             * @example 2026-05-16T02:09:22.467Z
             */
            timestamp: string;
            /** @description Response data or error details */
            data?: Record<string, never>;
        };
        UserResponseDto: {
            /** @example ff9660b6-20b5-42c2-8d20-9d44a2022278 */
            id: string;
            /** @example Mr. Ryan Donnelly */
            nombre: string;
            /** @example Lydia_Lemke@hotmail.com */
            email: string;
            /** @example 👤 */
            emoji?: Record<string, never> | null;
            /** @example 1-574-742-9017 x21184 */
            telefono?: Record<string, never> | null;
            /** @example 9847547856 */
            telegramChatId?: Record<string, never> | null;
            /** @example 1 */
            estudioId: number;
            /** @example {} */
            googleTokens?: Record<string, never> | null;
            /**
             * @example SOCIO
             * @enum {string}
             */
            role: "SOCIO" | "COLABORADOR";
            /** @example true */
            activo: boolean;
            /**
             * Format: date-time
             * @example 2025-08-22T10:35:22.799Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-05-16T00:29:07.984Z
             */
            updatedAt: string;
        };
        AuthResponseDto: {
            /** @example TwXge2Zz0SH8wt74uOP2BiUwlD7kzujgtXeEzfPj6ESIisYUp4pJyZeGhaxJUfyM */
            accessToken: string;
            /** @example OWCDST54KAcmAIiT6UUtYYdPzV7nrwi3ryESuSOK6GUYDppKuVPNL5djAn7Dej0J */
            refreshToken: string;
            user: components["schemas"]["UserResponseDto"];
        };
        UserLoginDto: {
            /** @example Shane.Hane@hotmail.com */
            email: string;
            /** @example 21xdu4ZLRG@@!44 */
            password: string;
        };
        UserCreateDto: {
            /** @example Shane.Hane@hotmail.com */
            email: string;
            /** @example 21xdu4ZLRG@@!44 */
            password: string;
            /** @example Dominick Metz PhD */
            nombre: string;
            /** @example 👤 */
            emoji?: string;
        };
        AuthRefreshResponseDto: {
            /** @example 8p5A6zogLuWQpnupdzLxth5RHloi21qIqu80nHiH77W3LSGCGVGR22UcvmQuERUy */
            accessToken: string;
        };
        ApiGenericResponseDto: {
            /**
             * @description Indicates if the operation was successful
             * @example true
             */
            success: boolean;
            /**
             * @description Response message
             * @example Operation completed successfully
             */
            message: string;
        };
        UserUpdateDto: {
            /** @example Geraldine.Hackett@yahoo.com */
            email?: string;
            /** @example Jack Quigley */
            nombre?: string;
            /** @example 👤 */
            emoji?: string;
            /** @example (656) 392-1426 x548 */
            telefono?: string;
        };
        UserGetProfileResponseDto: {
            /** @example ff9660b6-20b5-42c2-8d20-9d44a2022278 */
            id: string;
            /** @example Mr. Ryan Donnelly */
            nombre: string;
            /** @example Lydia_Lemke@hotmail.com */
            email: string;
            /** @example 👤 */
            emoji?: Record<string, never> | null;
            /** @example 1-574-742-9017 x21184 */
            telefono?: Record<string, never> | null;
            /** @example 9847547856 */
            telegramChatId?: Record<string, never> | null;
            /** @example 1 */
            estudioId: number;
            /** @example {} */
            googleTokens?: Record<string, never> | null;
            /**
             * @example SOCIO
             * @enum {string}
             */
            role: "SOCIO" | "COLABORADOR";
            /** @example true */
            activo: boolean;
            /**
             * Format: date-time
             * @example 2025-08-22T10:35:22.799Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-05-16T00:29:07.984Z
             */
            updatedAt: string;
        };
        UserUpdateProfileResponseDto: {
            /** @example ff9660b6-20b5-42c2-8d20-9d44a2022278 */
            id: string;
            /** @example Mr. Ryan Donnelly */
            nombre: string;
            /** @example Lydia_Lemke@hotmail.com */
            email: string;
            /** @example 👤 */
            emoji?: Record<string, never> | null;
            /** @example 1-574-742-9017 x21184 */
            telefono?: Record<string, never> | null;
            /** @example 9847547856 */
            telegramChatId?: Record<string, never> | null;
            /** @example 1 */
            estudioId: number;
            /** @example {} */
            googleTokens?: Record<string, never> | null;
            /**
             * @example SOCIO
             * @enum {string}
             */
            role: "SOCIO" | "COLABORADOR";
            /** @example true */
            activo: boolean;
            /**
             * Format: date-time
             * @example 2025-08-22T10:35:22.799Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-05-16T00:29:07.984Z
             */
            updatedAt: string;
        };
        ClienteResponseDto: {
            /** @example 1 */
            id: number;
            /** @example 1 */
            estudioId: number;
            /** @example 30-12345678-9 */
            cuit: string;
            /** @example Streich - Kihn */
            denominacion: string;
            /** @example 0 */
            termino: number;
            /** @example Responsable Inscripto */
            condicionIva: string;
            /**
             * @example [
             *       "Ventas al por mayor"
             *     ]
             */
            actividades: string[];
            /** @example 4282 Sandy Lane */
            domicilio?: Record<string, never> | null;
            /** @example (853) 420-0776 */
            telefono?: Record<string, never> | null;
            /** @example Johnathan_Stark@yahoo.com */
            email?: Record<string, never> | null;
            /** @example 292-586-9537 x2644 */
            whatsapp?: Record<string, never> | null;
            /** @example a300b786-3239-41f9-a25c-a931d8506c0a */
            encargadoId: string;
            /** @example a5db255f-484c-4556-b5d8-ded2294e6efc */
            supervisorId?: Record<string, never> | null;
            /**
             * @example ROJO
             * @enum {string}
             */
            semaforo: "VERDE" | "AMARILLO" | "ROJO";
            /** @example true */
            activo: boolean;
            /** @example Talis delectatio temperantia tero accendo commodi conscendo claustrum timor condico. */
            notas?: Record<string, never> | null;
            /**
             * Format: date-time
             * @example 2026-04-09T09:34:42.805Z
             */
            creadoEn: string;
        };
        ClienteImpuestoDto: {
            /** @example 1 */
            id: number;
            /**
             * @example IVA
             * @enum {string}
             */
            tipo: "AUTONOMOS" | "IVA" | "IIBB_LOCAL" | "MUNICIPAL" | "SUELDOS" | "MONOTRIBUTO" | "GANANCIAS";
            /** @example true */
            activo: boolean;
        };
        ClienteLegajoResponseDto: {
            /** @example 1 */
            id: number;
            /** @example 1 */
            estudioId: number;
            /** @example 30-12345678-9 */
            cuit: string;
            /** @example Streich - Kihn */
            denominacion: string;
            /** @example 0 */
            termino: number;
            /** @example Responsable Inscripto */
            condicionIva: string;
            /**
             * @example [
             *       "Ventas al por mayor"
             *     ]
             */
            actividades: string[];
            /** @example 4282 Sandy Lane */
            domicilio?: Record<string, never> | null;
            /** @example (853) 420-0776 */
            telefono?: Record<string, never> | null;
            /** @example Johnathan_Stark@yahoo.com */
            email?: Record<string, never> | null;
            /** @example 292-586-9537 x2644 */
            whatsapp?: Record<string, never> | null;
            /** @example a300b786-3239-41f9-a25c-a931d8506c0a */
            encargadoId: string;
            /** @example a5db255f-484c-4556-b5d8-ded2294e6efc */
            supervisorId?: Record<string, never> | null;
            /**
             * @example ROJO
             * @enum {string}
             */
            semaforo: "VERDE" | "AMARILLO" | "ROJO";
            /** @example true */
            activo: boolean;
            /** @example Talis delectatio temperantia tero accendo commodi conscendo claustrum timor condico. */
            notas?: Record<string, never> | null;
            /**
             * Format: date-time
             * @example 2026-04-09T09:34:42.805Z
             */
            creadoEn: string;
            impuestos: components["schemas"]["ClienteImpuestoDto"][];
            /** @example Alverta Okuneva */
            encargadoNombre: string;
            /** @example Dedrick Block V */
            supervisorNombre?: Record<string, never> | null;
        };
        CreateClienteDto: {
            /** @example 30-12345678-9 */
            cuit: string;
            /** @example Cummings, Labadie and Murphy */
            denominacion: string;
            /** @example Responsable Inscripto */
            condicionIva: string;
            /** @example 7e728279-987c-4661-a71c-501c57bd1889 */
            encargadoId: string;
            /** @example 0 */
            termino?: number;
            /**
             * @example [
             *       "Ventas al por mayor"
             *     ]
             */
            actividades?: string[];
            /** @example 4737 Lind Ridge */
            domicilio?: string;
            /** @example 339.940.1122 x897 */
            telefono?: string;
            /** @example Filomena_Haag@hotmail.com */
            email?: string;
            /** @example 1-835-333-1008 x23567 */
            whatsapp?: string;
            /** @example 219e9f08-7fd0-4ab5-9710-9ec831ffd408 */
            supervisorId?: string;
            /** @example Peior incidunt vilicus termes spectaculum. */
            notas?: string;
            /**
             * @example [
             *       "IVA",
             *       "GANANCIAS"
             *     ]
             */
            tipoImpuesto: ("AUTONOMOS" | "IVA" | "IIBB_LOCAL" | "MUNICIPAL" | "SUELDOS" | "MONOTRIBUTO" | "GANANCIAS")[];
        };
        UpdateClienteDto: {
            /** @example 30-12345678-9 */
            cuit?: string;
            /** @example Cartwright, Walker-Tillman and Marquardt */
            denominacion?: string;
            /** @example Responsable Inscripto */
            condicionIva?: string;
            /** @example 4606b2c4-2f9e-4694-9192-e55c22ccd5dd */
            encargadoId?: string;
            /** @example 0 */
            termino?: number;
            /**
             * @example [
             *       "Ventas al por mayor"
             *     ]
             */
            actividades?: string[];
            /** @example 96364 Troy Summit */
            domicilio?: string;
            /** @example 605-735-1516 x24313 */
            telefono?: string;
            /** @example Burnice_Herman95@yahoo.com */
            email?: string;
            /** @example 859.740.8462 x5316 */
            whatsapp?: string;
            /** @example c2517ab0-c804-4624-9146-de1246a95689 */
            supervisorId?: string;
            /** @example Arceo usus vinculum charisma sordeo theatrum. */
            notas?: string;
            /**
             * @example VERDE
             * @enum {string}
             */
            semaforo?: "VERDE" | "AMARILLO" | "ROJO";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthPublicController_login_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLoginDto"];
            };
        };
        responses: {
            /** @description auth.success.loggedIn */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSuccessResponseDto"] & {
                        /** @example 200 */
                        statusCode?: number;
                        /** @example auth.success.loggedIn */
                        message?: string;
                        /** @example 2026-05-16T02:09:22.780Z */
                        timestamp?: string;
                        data?: components["schemas"]["AuthResponseDto"];
                    };
                };
            };
        };
    };
    AuthPublicController_signup_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateDto"];
            };
        };
        responses: {
            /** @description auth.success.signedUp */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSuccessResponseDto"] & {
                        /** @example 201 */
                        statusCode?: number;
                        /** @example auth.success.signedUp */
                        message?: string;
                        /** @example 2026-05-16T02:09:22.805Z */
                        timestamp?: string;
                        data?: components["schemas"]["AuthResponseDto"];
                    };
                };
            };
        };
    };
    AuthPublicController_refreshTokens_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description auth.success.tokensRefreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSuccessResponseDto"] & {
                        /** @example 200 */
                        statusCode?: number;
                        /** @example auth.success.tokensRefreshed */
                        message?: string;
                        /** @example 2026-05-16T02:09:22.806Z */
                        timestamp?: string;
                        data?: components["schemas"]["AuthRefreshResponseDto"];
                    };
                };
            };
        };
    };
    AuthPublicController_getActiveUsers_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description auth.success.usersListed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiGenericResponseDto"];
                };
            };
        };
    };
    AuthPublicController_logout_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description auth.success.loggedOut */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiGenericResponseDto"];
                };
            };
        };
    };
    UserAdminController_findAll_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description user.success.list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiGenericResponseDto"];
                };
            };
        };
    };
    UserAdminController_findById_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description user.success.profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiGenericResponseDto"];
                };
            };
        };
    };
    UserAdminController_deleteUser_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description user.success.deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiGenericResponseDto"];
                };
            };
        };
    };
    UserAdminController_updateUser_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateDto"];
            };
        };
        responses: {
            /** @description user.success.updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiGenericResponseDto"];
                };
            };
        };
    };
    UserPublicController_getProfile_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description user.success.profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSuccessResponseDto"] & {
                        /** @example 200 */
                        statusCode?: number;
                        /** @example user.success.profile */
                        message?: string;
                        /** @example 2026-05-16T02:09:22.872Z */
                        timestamp?: string;
                        data?: components["schemas"]["UserGetProfileResponseDto"];
                    };
                };
            };
        };
    };
    UserPublicController_updateUser_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateDto"];
            };
        };
        responses: {
            /** @description user.success.updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSuccessResponseDto"] & {
                        /** @example 200 */
                        statusCode?: number;
                        /** @example user.success.updated */
                        message?: string;
                        /** @example 2026-05-16T02:09:22.872Z */
                        timestamp?: string;
                        data?: components["schemas"]["UserUpdateProfileResponseDto"];
                    };
                };
            };
        };
    };
    ClientesPublicController_findAll_v1: {
        parameters: {
            query: {
                search: string;
                semaforo: string;
                encargadoId: string;
                skip: string;
                take: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description clientes.success.list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiGenericResponseDto"];
                };
            };
        };
    };
    ClientesAdminController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClienteDto"];
            };
        };
        responses: {
            /** @description clientes.success.created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSuccessResponseDto"] & {
                        /** @example 201 */
                        statusCode?: number;
                        /** @example clientes.success.created */
                        message?: string;
                        /** @example 2026-05-16T02:09:22.853Z */
                        timestamp?: string;
                        data?: components["schemas"]["ClienteResponseDto"];
                    };
                };
            };
        };
    };
    ClientesPublicController_findById_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description clientes.success.retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSuccessResponseDto"] & {
                        /** @example 200 */
                        statusCode?: number;
                        /** @example clientes.success.retrieved */
                        message?: string;
                        /** @example 2026-05-16T02:09:22.860Z */
                        timestamp?: string;
                        data?: components["schemas"]["ClienteResponseDto"];
                    };
                };
            };
        };
    };
    ClientesAdminController_delete_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description clientes.success.clienteDeleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiGenericResponseDto"];
                };
            };
        };
    };
    ClientesAdminController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClienteDto"];
            };
        };
        responses: {
            /** @description clientes.success.updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSuccessResponseDto"] & {
                        /** @example 200 */
                        statusCode?: number;
                        /** @example clientes.success.updated */
                        message?: string;
                        /** @example 2026-05-16T02:09:22.853Z */
                        timestamp?: string;
                        data?: components["schemas"]["ClienteResponseDto"];
                    };
                };
            };
        };
    };
    ClientesPublicController_findLegajo_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description clientes.success.legajoRetrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiSuccessResponseDto"] & {
                        /** @example 200 */
                        statusCode?: number;
                        /** @example clientes.success.legajoRetrieved */
                        message?: string;
                        /** @example 2026-05-16T02:09:22.860Z */
                        timestamp?: string;
                        data?: components["schemas"]["ClienteLegajoResponseDto"];
                    };
                };
            };
        };
    };
    ClientesAfipController_getAfipData_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cuit: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description clientes.success.afipRetrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiGenericResponseDto"];
                };
            };
        };
    };
    HealthController_getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Health Check is successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example error */
                        status?: string;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up"
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect"
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                status: string;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
}
