import { SOCIO, COLABORADOR } from '@/constants';
import type { NavGroup } from '@/types';

export const navGroups: NavGroup[] = [
  {
    label: 'Principal',
    items: [
      {
        title: 'Dashboard',
        url: '/dashboard/overview',
        icon: 'dashboard',
        isActive: false,
        items: [],
        roles: [SOCIO, COLABORADOR],
      },
      {
        title: 'Clientes',
        url: '/dashboard/clientes',
        icon: 'building',
        shortcut: ['c', 'c'],
        isActive: false,
        items: [],
        roles: [SOCIO, COLABORADOR],
      },
      {
        title: 'Tareas',
        url: '/dashboard/tareas',
        icon: 'tasks',
        shortcut: ['t', 't'],
        isActive: false,
        items: [],
        roles: [SOCIO, COLABORADOR],
      },
      {
        title: 'Liquidaciones',
        url: '/dashboard/liquidaciones',
        icon: 'calculator',
        shortcut: ['l', 'l'],
        isActive: false,
        items: [],
        roles: [SOCIO, COLABORADOR],
      },
      {
        title: 'Vencimientos',
        url: '/dashboard/vencimientos',
        icon: 'calendarClock',
        shortcut: ['v', 'v'],
        isActive: false,
        items: [],
        roles: [SOCIO, COLABORADOR],
      },
      {
        title: 'Agenda',
        url: '/dashboard/agenda',
        icon: 'calendar',
        shortcut: ['a', 'a'],
        isActive: false,
        items: [],
        roles: [SOCIO, COLABORADOR],
      },
      {
        title: 'Comunicaciones',
        url: '/dashboard/comunicaciones',
        icon: 'mail',
        shortcut: ['m', 'm'],
        isActive: false,
        items: [],
        roles: [SOCIO, COLABORADOR],
      },
      {
        title: 'Archivos',
        url: '/dashboard/archivos',
        icon: 'paperclip',
        shortcut: ['f', 'f'],
        isActive: false,
        items: [],
        roles: [SOCIO, COLABORADOR],
      },
      {
        title: 'Notificaciones',
        url: '/dashboard/notificaciones',
        icon: 'notification',
        shortcut: ['n', 'n'],
        isActive: false,
        items: [],
        roles: [SOCIO, COLABORADOR],
      },
      {
        title: 'Usuarios',
        url: '/dashboard/users',
        icon: 'user',
        shortcut: ['u', 'u'],
        isActive: false,
        items: [],
        roles: [SOCIO],
      },
      {
        title: 'Plantillas Email',
        url: '/dashboard/email-templates',
        icon: 'mail',
        shortcut: ['e', 'e'],
        isActive: false,
        items: [],
        roles: [SOCIO],
      },
      {
        title: 'Financiero',
        url: '/dashboard/financiero',
        icon: 'trendingUp',
        shortcut: ['i', 'i'],
        isActive: false,
        items: [],
        roles: [SOCIO],
      },
    ],
  },
];
